In [3]:
import torch

# =========================
# Day 14 - Part 0: 版本與環境確認
# =========================
print("torch version:", torch.__version__)
print("cuda available:", torch.cuda.is_available())
print("-" * 60)

# =========================
# Day 14 - Part 1: Tensor 基本建立與屬性
# =========================
# 1) 建立 1D Tensor（向量）
x = torch.tensor([1.0, 2.0, 3.0])

print("[Part 1] x =", x)
print("shape:", x.shape)      # 形狀
print("dtype:", x.dtype)      # 資料型別
print("device:", x.device)    # 在 CPU 或 GPU
print("-" * 60)

# 2) 建立 2D Tensor（矩陣）
A = torch.tensor([[1.0, 2.0],
                  [3.0, 4.0]])

print("[Part 1] A =\n", A)
print("shape:", A.shape)
print("-" * 60)

# 3) 常見初始化方式：random / zeros / ones
R = torch.randn(3, 4)         # 3x4 的常態分布亂數
Z = torch.zeros(2, 3)         # 2x3 全 0
O = torch.ones(2, 3)          # 2x3 全 1

print("[Part 1] R shape:", R.shape)
print("[Part 1] Z =\n", Z)
print("[Part 1] O =\n", O)
print("-" * 60)

# =========================
# Day 14 - Part 2: Tensor 運算（逐元素 vs 矩陣乘法）
# =========================
B = torch.tensor([[5.0, 6.0],
                  [7.0, 8.0]])

print("[Part 2] A + B =\n", A + B)       # 逐元素相加
print("[Part 2] A * B =\n", A * B)       # 逐元素相乘（element-wise）
print("[Part 2] A @ B =\n", A @ B)       # 矩陣乘法（matmul）
print("[Part 2] torch.matmul(A, B) =\n", torch.matmul(A, B))
print("-" * 60)

# =========================
# Day 14 - Part 3: Shape 思維（神經網路最重要）
# =========================
# 假設一個 mini-batch：4 筆資料，每筆 2 個特徵
X = torch.randn(4, 2)  # (batch=4, features=2)

# 一層線性層：2 -> 3
W = torch.randn(2, 3)  # (in=2, out=3)
b = torch.zeros(3)     # (out=3,) 會自動 broadcast

Z_linear = X @ W + b   # (4,2) @ (2,3) -> (4,3) 然後 + (3,) broadcast

print("[Part 3] X shape:", X.shape)
print("[Part 3] W shape:", W.shape)
print("[Part 3] b shape:", b.shape)
print("[Part 3] Z_linear shape:", Z_linear.shape)
print("-" * 60)

# =========================
# Day 14 - Part 4: Autograd（自動微分） - 單變數例子
# =========================
# requires_grad=True 表示：我想要對 x 求梯度
x = torch.tensor(2.0, requires_grad=True)

# 定義一個函數 y(x) = x^2 + 3x + 1
y = x**2 + 3*x + 1

# backward() 會把 y 對 x 的導數算出來，存到 x.grad
y.backward()

print("[Part 4] x =", x.item())
print("[Part 4] y =", y.item())
print("[Part 4] dy/dx (x.grad) =", x.grad.item())  # 應該是 7
print("-" * 60)

# =========================
# Day 14 - Part 5: Autograd（向量/矩陣） - 線性回歸的核心形式
# =========================
# 這段是你之後 Day 15/16 training loop 的基礎
# 我們做一個最小例子：y_pred = Xw + b，並對 w/b 求梯度

# 4筆資料、2特徵
X = torch.tensor([[1.0, 2.0],
                  [2.0, 1.0],
                  [3.0, 4.0],
                  [4.0, 3.0]])

# 真實 y（假設是某個線性規則產生）
Y = torch.tensor([[1.0],
                  [1.0],
                  [2.0],
                  [2.0]])

# 參數 w, b 要求梯度
w = torch.randn(2, 1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# forward
y_pred = X @ w + b  # (4,2)@(2,1)->(4,1)

# loss：MSE（均方誤差）
loss = torch.mean((y_pred - Y) ** 2)

# backward：自動算出 dw, db
loss.backward()

print("[Part 5] loss =", loss.item())
print("[Part 5] w shape:", w.shape, "b shape:", b.shape)
print("[Part 5] dw =\n", w.grad)
print("[Part 5] db =\n", b.grad)
print("-" * 60)

print("Day 14 done ✅")

torch version: 2.10.0+cpu
cuda available: False
------------------------------------------------------------
[Part 1] x = tensor([1., 2., 3.])
shape: torch.Size([3])
dtype: torch.float32
device: cpu
------------------------------------------------------------
[Part 1] A =
 tensor([[1., 2.],
        [3., 4.]])
shape: torch.Size([2, 2])
------------------------------------------------------------
[Part 1] R shape: torch.Size([3, 4])
[Part 1] Z =
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
[Part 1] O =
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
------------------------------------------------------------
[Part 2] A + B =
 tensor([[ 6.,  8.],
        [10., 12.]])
[Part 2] A * B =
 tensor([[ 5., 12.],
        [21., 32.]])
[Part 2] A @ B =
 tensor([[19., 22.],
        [43., 50.]])
[Part 2] torch.matmul(A, B) =
 tensor([[19., 22.],
        [43., 50.]])
------------------------------------------------------------
[Part 3] X shape: torch.Size([4, 2])
[Part 3] W shape: torch.Size([2, 3])
[P