In [ ]:
# np.zeors(1,1) tuple
# np.zeros([1,1]) list

In [1]:
import numpy as np
# 一維陣列
data=np.array([3,2,6,4])
print(data)
data=np.empty(4)#創造一個有四個資料的一維陣列,資料未指定
print(data)
data=np.zeros(3)
print(data)
data=np.ones(3)
print(data)
data=np.arange(5)
print(data)



[3 2 6 4]
[2.16851034e+243 4.27242994e+180 2.18188368e+243 3.34901064e-317]
[0. 0. 0.]
[1. 1. 1.]
[0 1 2 3 4]


In [3]:
# 二維陣列
import numpy as np
data=np.array([ #3x3二維陣列
    [2,3,2],
    [1,5,2],
    [4,2,1]
])
print(data)
data=np.empty([3,3])#創造一個3x3的二維陣列,資料未指定
print(data)
data=np.ones([2,3])
print(data)

[[2 3 2]
 [1 5 2]
 [4 2 1]]
[[0.0e+000 0.0e+000 0.0e+000]
 [7.9e-322 4.0e-323 7.9e-322]
 [4.0e-323 7.9e-322 4.0e-323]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
# 三維陣列
data=np.array([  #2X2X2的三維陣列
    [
        [3,1],[1,2]
    ],
    [
        [2,5],[10,2]
    ]
])
print(data)
data=np.zeros([3,1,3])
print(data)

[[[ 3  1]
  [ 1  2]]

 [[ 2  5]
  [10  2]]]
[[[0. 0. 0.]]

 [[0. 0. 0.]]

 [[0. 0. 0.]]]


In [17]:
# 高維陣列
data=np.array([#1X1X2X3的高維陣列
    [
        [
            [3,2,1],
            [5,5,10]
            
        ]
    ]
])
print(data)
data=np.ones([2,1,1,2])
print(data)

[[[[ 3  2  1]
   [ 5  5 10]]]]
[[[[1. 1.]]]


 [[[1. 1.]]]]
