In [1]:
import numpy as np
# 逐元運算(elementwise) #shape要一模一樣
data1=np.array([2,3,10])
data2=np.array([1,3,6])
result=data1+data2
print(result)
result=data1*data2
print(result)
result=data1>data2
print(result)
result=data1==data2
print("是否相等",result)

[ 3  6 16]
[ 2  9 60]
[ True False  True]
是否相等 [False  True False]


In [ ]:
# 矩陣運算(matrix) 矩陣 = 二維陣列（2D array）
data1=np.array([#1*2
    [1,3]
])                      #內積2需對上2才能算col=row
data2=np.array([#2*3
    [2,-1,3],
    [-2,4,1]
])                      #shape=1x3 
# result=data1.dot(data2)
result=data1@data2 #內積
print(result)
print("-------------------")
result=np.outer(data1,data2)#2(1*2)X6(2*3) 外積
print(result)

[[-4 11  6]]
-------------------
[[ 2 -1  3 -2  4  1]
 [ 6 -3  9 -6 12  3]]


In [13]:
# 統計運算(satistics) ndarray多維陣列
import numpy as np
data=np.array([
    [2,1,7],
    [-5,3,8]
])#2x3 
# result=data.cumsum(axis=0)
# print(result)
result=data.sum(axis=0)#針對colum第一個維度做總和
print(result)
result=data.sum(axis=1)
print(result)#針對row第二個維度做總和
result=data.max(axis=0)
print(result)
result=data.mean(axis=1)
print(result)
# result=data.sum()
# print("總和",result)
# result=data.max()
# print("最大值",result)
# result=data.mean()
# print("平均數",result)
# result=data.std()
# print("標準差",result)

[-3  4 15]
[10  6]
[2 3 8]
[3.33333333 2.        ]
