In [6]:
# # Indexing索引
# # 單維度
import numpy as np
# data=np.array([1,2,3,4,])
# print(data[2])
# #多維度
# data=np.array([
#     [1,2],
#     [4,5],
#     [7,8]
# ])
# print(data[0,1])
# # 多維陣列的切片:Slicing
# # 單維切片
# data=np.array([1,2,3,4])
# print(data[0:3])
# print(data[:2])
# print(data[:])
# # 多維度切片
# data=np.array([
#     [1,2,3],
#     [4,5,6],
#     [7,8,9],
#     [10,11,12]

# ])
# print(data[1:3,0:2])
# print(data[0:2,:])
#使用...代表全部
data=np.array([
    [
        [1,2,3],[4,5,6]
    ],
    [
        [7,8,9],[10,11,12]
    ]
])#2x2x3
print(data[0,...])#維度2 data[0,:,:]
print("----------")
print(data[0:2,1,0:2])#data=[ 層範圍 , 列 , 行範圍 ]
print("-------")
print(data[...,1:3])#維度3 data[:,:,1:3]
# 整數索引 → 維度會消失 01234
# slicing → 維度會保留 :
#None新增一個維度 長度為1


[[1 2 3]
 [4 5 6]]
----------
[[ 4  5]
 [10 11]]
-------
[[[ 2  3]
  [ 5  6]]

 [[ 8  9]
  [11 12]]]
