In [1]:
import numpy as np
data=np.ones(10)
print(data.shape)   
data=np.array([
    [3,1,5],
    [1,2,3]
])
print(data.shape)
# 資料轉置
data=np.array([
    [2,4,1],
    [1,5,0]
])
print(data.shape)#(2,3)
print(data.T)#(3,2)
# 扁平化資料
data=np.array([
    [
        [11,12,13],[14,15,16],[17,18,19]
    ],
    [
        [1,2,3],[4,5,6],[7,8,9]
    ]
])#(2,3,3)
print(data.shape)
newData=data.ravel()
print(newData)
# 重塑資料形狀
data=np.array([
    [
        [11,12,13],[14,15,16]
    ],
    [
        [1,2,3],[4,5,6]
    ]
])#2x2x3=12
newData=data.reshape(3,4)#3x4=12
print(newData)#總資料數要相同
data=np.zeros(18).reshape(3,6)
print(data)
data=np.arange(9).reshape(1,3,3)
print(data)

(10,)
(2, 3)
(2, 3)
[[2 1]
 [4 5]
 [1 0]]
(2, 3, 3)
[11 12 13 14 15 16 17 18 19  1  2  3  4  5  6  7  8  9]
[[11 12 13 14]
 [15 16  1  2]
 [ 3  4  5  6]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
